---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks

- Developer:
    - Github:
        - abbr: GH
          icon: github.png
          href: https://github.com/LukeHagar

- Social:
    - Reddit:
        - abbr: RE
          icon: reddit.png
          href: https://reddit.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          icon: youtube.png
          href: https://youtube.com/
