---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- Applications:
    - Echo Server:
        icon: mdi-api
        href: https://echo.plygrnd.org/
        description: HTTP Echo Test Server
        namespace: default
        app: echo
    - Homepage:
        icon: homepage.png
        href: https://homepage.plygrnd.org/
        description: Dashboard
        namespace: default
        app: homepage

- Networking:
    - Envoy Gateway:
        icon: envoyproxy.png
        description: Gateway API Controller
        namespace: network
        app: envoy-gateway
    - K8s Gateway:
        icon: mdi-dns
        description: Internal DNS Gateway
        namespace: network
        app: k8s-gateway
    - Cloudflare Tunnel:
        icon: cloudflare.png
        description: Secure Tunnel
        namespace: network
        app: cloudflare-tunnel
    - Cloudflare DNS:
        icon: cloudflare.png
        description: External DNS
        namespace: network
        app: external-dns-cloudflare

- Infrastructure:
    - Cilium:
        icon: cilium.png
        description: CNI & Network Policy
        namespace: kube-system
        app: cilium
    - CoreDNS:
        icon: coredns.png
        description: Cluster DNS
        namespace: kube-system
        app: coredns
    - Metrics Server:
        icon: kubernetes.png
        description: Resource Metrics API
        namespace: kube-system
        app: metrics-server
    - Spegel:
        icon: mdi-content-copy
        description: Container Registry Mirror
        namespace: kube-system
        app: spegel
    - Reloader:
        icon: mdi-reload
        description: ConfigMap/Secret Reload
        namespace: kube-system
        app: reloader

- GitOps:
    - Flux Operator:
        icon: flux-cd.png
        description: GitOps Operator
        namespace: flux-system
        app: flux-operator
    - Flux Instance:
        icon: flux-cd.png
        description: Cluster Reconciliation
        namespace: flux-system
        app: flux

- Security:
    - Cert Manager:
        icon: cert-manager.png
        description: Certificate Management
        namespace: cert-manager
        app: cert-manager
