apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:mQI6ohwgVgAL1+Q2Ax9W8zGdSCAamPkkNvYKdFXmVjGmHefLh8USaQ==,iv:/p9nnrBWmjLiAozR7EjS4/F4Bkfzl91uxis7NUzrGRU=,tag:W41CInsUZK0Cl2q7beHlrg==,type:str]
sops:
  age:
    - recipient: age1uau898xek2nz2pru9guhcln7jn2p5cz2exl20evhhcr9zyl59ypq6h8kfy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2STVuU0k3aVpZUmI4RU5u
        Mis3NUNVV2E0ZHZwdDdDU25CL1l6bWIwUGp3Cjc5eDZ1ZG14QjA3dTAxQlJlcjc5
        c3d3OWRvdks5YTZBcER6YTM2WEd4a0UKLS0tIE5ZQW1oMHdyaldQWjNPS1owRzA4
        Y0NjaUI1QzBBeFpYdUF0d3dmLzN0bXcKfVWcv5E53YuVFlujTzcbziZxJDC4RYaJ
        qMsmxWi/k6K1Q3IodYyKxZmsg/271KxF9VHpvSwMXy2gADeVJ2hczA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T04:26:59Z"
  mac: ENC[AES256_GCM,data:flLsKnmmGLmpxQOLIKLBNbWww6wmUBdkZsU0AYEdSyxAkrums9tcXukOq4FS8xi9hOxm3Te9ypetR/PVN0f6cUIo7HTBRDwi/vRigPoWPuDTRExNmCWukBySE2U5V+jmBRjqoiMDmzCCMDRv67SQAAAeBE5qGv18PmrTdj+o4u8=,iv:yut3gappQq7M/uXZJvlbRUoRaRZWUdHUqb0TaEUmKUQ=,tag:vom5fJPWLXlbzuKbjPXhyQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
