apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:tOj8JVQmS2rVqSU=,iv:PQEWNA4RJ82dDGIK7gqFfJEhW+v8RJi6TA7A064hsoo=,tag:yXfuLdzZGL/J74T+bxP0FA==,type:str]
sops:
  age:
    - recipient: age1uau898xek2nz2pru9guhcln7jn2p5cz2exl20evhhcr9zyl59ypq6h8kfy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTW1FRWg0ZWVHdzN3dmdo
        aGtiK0dUREs0MVRpY2kzUEtaRUdmREEzcFRnClBWdmtkWTRkMmtIMHdmM0dVaEw1
        R3U1TnlDVlU0VVZ2RThoaXJqdzM5dlkKLS0tIDArRlNJTS9vckFqcDg1VkRGOHlV
        QkZNZDdJMTJXZTZCMTJNY1ljQjUyZEEKjbUAhmiXbYXfyd5TvGtlVkKuolyBHovy
        4MNP6LV3FAGDwqXlnZkjaOhD5OONH1SUiL/v4AmFL4xzl4PFQ0sSpQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T04:26:59Z"
  mac: ENC[AES256_GCM,data:XUx3fC8PvMrHlDsl+H8t7+MIp5frRv8Im8f6dZFadvFtx9ah0gd9yd55OQzUmiugsshhmmVdi3NSDSaslnTxnKqHKqXrAMoCNpROFO/CYHbMyp2LKhni9Pmr5LKeA+FJAaHWWbYxJoXJCxF9ymOZokPwXi2QlD2mmXxg2M9Mm9k=,iv:xwjS/k/6oGmW5nX+G4JUGbzI5Qzs4sZLgRVPm+27HO4=,tag:30KM68SDxyU+hRDW8+5oqQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
