apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:EUgDPK16CHwiEC+M89ieaV/1sQ+Gq3aChnlHcNliBOQ=,iv:jtSrp4nCsPlUdIB0Hws35tdh9KCpvlCQQzn+YfQMJyA=,tag:jZ5sl8jqugb2vEftcRRMSQ==,type:str]
sops:
  age:
    - recipient: age1uau898xek2nz2pru9guhcln7jn2p5cz2exl20evhhcr9zyl59ypq6h8kfy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwOE9zc1JEZnh6UVFIVThT
        WVBHSEJmK1l2Ym5yWEh0SklURmtReTM3Um1nCmlhTlZkM3M1WCtZN2FZZ1pPZjdI
        dWRtVWlZR1JwekRTY1ZMd3M1aTNaclEKLS0tIFlzaFJ1MDg3TVhFUVFhdk5ISVJR
        Zkd0WTBmRWFqTDVDME1GUjIrcjJjWGMKjTI5rx1MuynZRw5T4oUggZ3LW4+C4RCs
        4oHRjoxm1CJ64hbibeP99MX+feWVFdeJK7Zhe6D+vZ4gbq20meedQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T04:26:59Z"
  mac: ENC[AES256_GCM,data:GqoHsi8/9GMeZJW98HhCJURL/jdnmK9WrvjvSVJ/W+009wQrSH8LBBokYcFA4jQuA8M8fw6vbP60MDy/CuT4vu0FR/kwoZ9ZdVCK+xe7zSUf9xJ8yOr37bjoo4tHY0yyhQcos1VzQQXB5Wz6WVoRko9gxDTO39EEW1g5dSZiy9o=,iv:LmCXFhBdbNSpWK8qU4bqmHxm7Yk56bM6wGpM9wE6QsA=,tag:+TB+r6KzNTIBWlrTnzJsxA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
