apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:fvEUGHzD+IAW2kXSI4nFLnbVrWFMMeOV+xq1mLf970YVZ3C/CGgSPOSM9uwXyw1uJqzIg5p3Vw2My9A6Zj31LietVSpr2baPBfujO//sGdfFaPO22sujQeuQm8muAyAeUZP/1hOXwKpxmps2AdRrqCuRsEdx0voRS8m5+kuuRWxU5eJWMyeIHVhaHtnmTzwQZpZObbm+FD7Ik+d8wujs8lPPQz8mN3nzS6K9BW24W4BzJs9g,iv:wZ3SymPm9je+htnohmmLEyI+HTo9SBp3m+k2JWqi74g=,tag:8FZNr/4m7nqEoHXaaFKb+g==,type:str]
sops:
  age:
    - recipient: age1uau898xek2nz2pru9guhcln7jn2p5cz2exl20evhhcr9zyl59ypq6h8kfy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqclBIUlJ0SURwU25OM0x5
        dVhZYnZCdDVKZUNWV01IUDRuZnBqT3I5aGtrCkluRkllQUNPazFLcXgyUTlQTVBv
        TmUwMmhYU2JjS3RmcW8xZjRCaERtZnMKLS0tIGtoTW10dkM2Mmc4alpteXNZaW93
        d1o0dTB3QTcyak9iUkxqRGlZOG81ZWcKvL9ymo8ogO5sJcSZoXjMiWScBaZx3nQU
        Rel1bwPAEF3TPMyueh/qAHxvWOh1bExIkRbhZNQ9sURXeZmuB0h/vw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T04:26:59Z"
  mac: ENC[AES256_GCM,data:ioZPjFS5u5FBnkcf4mx/oYxnkQ9FlkWk/TWeVzyelV6HR6s6ZBvhT68wZ5VinZR3pR7Vld3p7wyTMeSEsemcoYSmbitblaO+CF703pwm216Z7f99j+ebMnP2F5zk3AuWpcfSepe0E+7AVukLR0MrYITJ4T2j8GouPsVLzsLUax8=,iv:j4ei67isA7GndmNJ5ygLex5TxKsYbA9Zi5QBLhEs7gE=,tag:S2zQyKAShxN5xxKbzF+Ekw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
