apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:vnxAd63xf/CMKTcv5DIRbJsm/cl5BWiWCQv9YWYPM511SDc49J6V+w==,iv:Hh6eUce0DduRa9VQ5OKGWAUsppdfD7sMQIHOAlQ1l3Q=,tag:ki9JTuQVWpl1fhCSKPA/zQ==,type:str]
sops:
  age:
    - recipient: age1uau898xek2nz2pru9guhcln7jn2p5cz2exl20evhhcr9zyl59ypq6h8kfy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZmtlSHVtUXg5K2dLLzg4
        T1lMQWVZOUwrYUh1OG5yWkxwRU5scVRKV2lFCnlWZ3lKZnlmTlVMTHVoMmVUTXky
        V2hLbGo0V0l1MjBlTHVhd2hlOFFlQWcKLS0tIEgrU0VLZTFHc1VxQ2s0ZnRXT2oz
        alJzNW9zUkpMOHZIUmIwZGY1aWpCRUEKeWTYtr49Li4bRAbthv76P7+13OyN8dEA
        FimasHzSNtxDmHOaqtzfA2R/8c0JdY1829g33TlJKdYk/pfrhFABrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-04T04:26:59Z"
  mac: ENC[AES256_GCM,data:ZyMJXOkiZOUXCJmpsQlKIXTHSuS5goSLpNBiQdqhISHz+7ImOiLtNGEaSfF1OLldECByL/3F9wHYnSNrmKUX9wRVmtYhtpyyTHmo3OdcIlbi80R1W2IEQOl8S0XDZHmkffkgQGD8vJEBaeeX0VZPZPVwK7nvmjhtVeEnyoOZPI4=,iv:rkvRqJEP0a3gy/60sYMgWVqBelW4+RDyR2KTrevg/Ss=,tag:0yDTVGG1LdHkTTV47YyYfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
