---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.10.59:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.10.10.59"
  - "talos.plygrnd.org"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-1"
    ipAddress: "10.10.10.51"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2c:cd:eb"
        dhcp: false
        addresses:
          - "10.10.10.51/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"
  - hostname: "talos-2"
    ipAddress: "10.10.10.52"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:15:be:9d"
        dhcp: false
        addresses:
          - "10.10.10.52/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"
  - hostname: "talos-3"
    ipAddress: "10.10.10.53"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:71:01:1d"
        dhcp: false
        addresses:
          - "10.10.10.53/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"
  - hostname: "talos-4"
    ipAddress: "10.10.10.54"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:50:61:c3"
        dhcp: false
        addresses:
          - "10.10.10.54/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"
  - hostname: "talos-5"
    ipAddress: "10.10.10.55"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:a3:d6:3c"
        dhcp: false
        addresses:
          - "10.10.10.55/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"
  - hostname: "talos-6"
    ipAddress: "10.10.10.56"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:ec:06:4f"
        dhcp: false
        addresses:
          - "10.10.10.56/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"
  - hostname: "talos-7"
    ipAddress: "10.10.10.57"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:9a:35:b1"
        dhcp: false
        addresses:
          - "10.10.10.57/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"
  - hostname: "talos-8"
    ipAddress: "10.10.10.58"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:28:4a:f0"
        dhcp: false
        addresses:
          - "10.10.10.58/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.10.1"
        mtu: 1500
        vip:
          ip: "10.10.10.59"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

