---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "plygrnd-org-certificate"
spec:
  secretName: "plygrnd-org-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: plygrnd.org
  dnsNames:
    - "plygrnd.org"
    - "*.plygrnd.org"
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "gitwatch-dev-certificate"
spec:
  secretName: "gitwatch-dev-tls"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: gitwatch.dev
  dnsNames:
    - "gitwatch.dev"
    - "*.gitwatch.dev"
